### PR TITLE
Reflow script

### PR DESCRIPTION
**Pull request by phyver**
OK, here is what I had in mind.

Calling `box.sh`` (for example via the `parchment` script) will do the following:
 - get the size of the terminal (`$COLUMNS)
 - if this size is strictly less than 80, the text is reformated but no parchment is added
 - if the size is more than 80, the text is reformated at width `$COLUMNS-30`, and a parchment is added.
   (30 should be enough so that all boxes will still fit in the terminal

the `reflow.awk` script works as follows:
  - line ending with a trailing space *do not end a paragraph*, lines without a trailing space *end a paragraph*.
  - empty lines end a paragraph, as does the end of file
  - the indentation of the first line of the paragraph is kept throughout the paragraph
  - list items are recognized (`/^ *[-+]  */` or `/^ *[0-9][0-9]*  */` so that the indentation of the text is kept throughout the paragraph.

There are a couple of goal files that could require some tweaking:
  - `finding_files/03`
  - `finding_files/04`
  - `misc/02`
  - `misc/03`
  - `pipes_merchant_stall/01`
  - `pipes_merchant_stall/02`
  - `processes/02`
  - `processes/03`
  - `stdin_stdout_stderr/03`
  - `stdin_stdout_stderr/04`

For example, the text
```
man COMMAND
  Display the manual of the command.

  Important key bindings:
    q           quit
    Space       scroll down one page
    / STRING    search for the string
    n           find the next occurrence for the search string
```
is transformed into
```
man COMMAND
  Display the manual of the command.

  Important key bindings:
    q quit
    Space scroll down one page
    / STRING search for the string
    n find the next occurrence for the search string
```
because consecutive spaces are merged.

@rlepigre 
What do you think?

### CODE REVIEW

**Comment by rlepigre** [comment]
That sounds reasonable, except one point: I would not use the whole width of the terminal if it is very wide. For instance if I have a full-screen terminal window on my machine I have 239 columns. I think think the parchments would be quite ugly if there were so wide. I think we should never go above 100 columns (including the parchment), and maybe something even narrower would look nicer (and be easier to read). What do you think?

For the rest, I'll need to see how it looks like!

**Comment by phyver** [comment]
That's what I wanted to do at first, but couldn't decide where to put the limit.
I tried on a couple of files, and even at 175 characters wide, it still looked good.
Try it and tell me what you think...

**Comment by rlepigre** [comment]
I tried a few things, and I noticed two things:
- I really don't like to not have any parchment in a narrow terminal, the goal is harder to read since it is hard to spot where it starts.
- Some of the parchments do not take up much space: maybe we should just decide to only use these on narrow terminals.
- We could add a minimal parchment (a simple box) that would only add 4 characters of width, to use in extreme cases.

I don't expect anyone is using a terminal with less than 60 columns, so I don't think we should care too much about that. But even if that happens I think we should still have a parchment (even if it is just a box).

**Comment by rlepigre** [comment]
But overall, I think this is all pretty neat! :)

**Comment by phyver** [comment]
Better?

I also added "protected lines": a paragraph with a single line starting with 2 or more spaces and containing another sequence of 2 or more spaces is output without wrapping.

That allows to align small tables like
```
    q           quit
    Space       scroll down one page
    / STRING    search for the string
    n           find the next occurrence for the search string
```

**Comment by rlepigre** [comment]
Yeah, that's better for narrow terminals, but I saw that when the simple box is used there is weird output at the top:
```
[mission 1] $ gsh goal
BOX=

+-------------------------------------------------+
| Mission goal                                    |
| ============                                    |
```

I still don't like when goals get very wide, but I don't hate it either.

Is there an easy way to generate a file containing all the goals / treasures as would be printed with `N` available columns?
That would be convenient to check that things look OK on all goals.

**Comment by phyver** [comment]
from `$GSH_ROOT`:
```
$ find -path "*goal/*.txt" -exec ./bin/box.sh -R 100 -B Parchment6 {} \; 
```

**Comment by phyver** [comment]
> Is there an easy way to generate a file containing all the goals / treasures 
>
I'll have to reflow treasures as well!

**Comment by phyver** [comment]
If everything works, I'll merge that tonight and merge devel onto master.
That will be release 0.2, and I'll send it for testing...

**Comment by rlepigre** [comment]
> If everything works, I'll merge that tonight and merge devel onto master.
> That will be release 0.2, and I'll send it for testing...

OK great! I'll send it around for testing as well once you have merged then. :)

**Comment by phyver** [comment]
squashed and merged: cfc9192fe2cd8b8e8c6f2f50f8c90ab5fe0ea071

**Pull request closed without merging**
